### ISSUE TITLE
heightCalculationMethod on nuxt

### ISSUE THREAD

**Issue by rustynail1984** [davidjbradshaw/iframe-resizer#1064]
im trying to use the heightCalculationMethod: 'taggedElement' option on nuxt 

My iframe page:

```
<iframe
      v-resize="{ log: true, heightCalculationMethod: 'taggedElement'}"
      :id="iframeId"
      :src="PreUrl"
      width="100%"
      height="100%"
      allowtransparency="true"
      scrolling="no"
      style="border: none">
</iframe>
```

```
<script>
...

directives: {
    resize: {
      bind(el, { value = {} }) {
        el.addEventListener("load", () => iframeResize(value, el));
      },
    },
 },
<script>
```

My Content Page:

```
<template>
<div>
  <div class="flex flex-wrap place-content-center gap-4 justify-center mx-auto p-2" data-iframe-height>
    <SearchCard v-for="s in search" :key="s.key" :data="s"/>
  </div>
</div>
</template>
```

Browser Console:
`iframeResizer.contentWindow.js:170 [iFrameSizer][searchApi] No tagged elements (data-iframe-height) found on page`

Someone has an idea why `data-iframe-height` is not found?

**Comment by taufeeq-zaman** [comment]
> im trying to use the heightCalculationMethod: 'taggedElement' option on nuxt
> 
> My iframe page:
> 
> ```
> <iframe
>       v-resize="{ log: true, heightCalculationMethod: 'taggedElement'}"
>       :id="iframeId"
>       :src="PreUrl"
>       width="100%"
>       height="100%"
>       allowtransparency="true"
>       scrolling="no"
>       style="border: none">
> </iframe>
> ```
> 
> ```
> <script>
> ...
> 
> directives: {
>     resize: {
>       bind(el, { value = {} }) {
>         el.addEventListener("load", () => iframeResize(value, el));
>       },
>     },
>  },
> <script>
> ```
> 
> My Content Page:
> 
> ```
> <template>
> <div>
>   <div class="flex flex-wrap place-content-center gap-4 justify-center mx-auto p-2" data-iframe-height>
>     <SearchCard v-for="s in search" :key="s.key" :data="s"/>
>   </div>
> </div>
> </template>
> ```
> 
> Browser Console: `iframeResizer.contentWindow.js:170 [iFrameSizer][searchApi] No tagged elements (data-iframe-height) found on page`
> 
> Someone has an idea why `data-iframe-height` is not found?

have you found any solutions?

**Comment by rustynail1984** [comment]
> have you found any solutions?

nope

**Comment by davidjbradshaw** [comment]
I'm afraid I never used Nuxt. This might be more a question for StackOverflow

**Comment by nynevi** [comment]
unfortunately the package needs a bit of improvement for the taggedElement behavior. It stops when it cannot find a taggedElement but in the case of JS frameworks, elements rendered on the page may not be available the time iFrameResizer calls resize but some milliseconds later.

I ended up implementing a retry mechanism. it is not reliable, as the time it takes to render the element on JS frameworks varies, but it handles my use cases.

the code looks somewhat like this, adapt to your own use case:
```ts
        resizerResizeInterval: number | undefined = undefined
        resizerResizeIntervalIteration: number = 0
        resizerResizeIntervalTimeout: number = 1000
        resizerResizeIntervalIterationTimer: number = 50

        tryResize(iframe: HTMLIFrameElement) {
            this.resizerResizeInterval = setInterval(() => {
                if (
                    this.resizerResizeIntervalIteration *
                        this.resizerResizeIntervalIterationTimer >=
                    this.resizerResizeIntervalTimeout
                ) {
                    clearInterval(this.resizerResizeInterval)
                    this.resizerResizeInterval = undefined
                    ;(iframe as any).iFrameResizer?.resize()
                } else {
                    ;(iframe as any).iFrameResizer?.resize()
                    this.resizerResizeIntervalIteration += 1
                }
            }, this.resizerResizeIntervalIterationTimer) as unknown as number
        }
```

it is worth mentioning that, this retry mechanism, in my opinion, should be built in the package itself. maybe it already does through the MutationObserver but in the case of `taggedElement` strategy, I don't see any logs/warnings being printed when MutationObserver is triggers resize. This may be a bug or just lack of a retry mechanism.

Alternatively if it is not desired to add such retry mechanism to the package, we would need event callbacks while initializing the iFrameResizer, something along the lines of:
```js
onTaggedElementFound: () => {},
onTaggedElementNotFound: () => {}
```

I have solved the issue temporarily to save the day and I'm highly sure that the unreliable timeouts etc will cause an issue next week on some of the iframes therefore I'll try to help by adding the above callbacks to the package through a PR so that we can do:

pseudo code:
```js
const stopPolling = () => {
    //remove interval
}

const startPolling = (iframe) => {
   if timeout reached
      stopPolling()
   else
      keep calling iframe.iFrameResizer.resize()
}

onTaggedElementNotFound: () => {
   startPolling()
},
onTaggedElementFound: () => {
   stopPolling()
}
```

**Comment by davidjbradshaw** [comment]
Would it not be simpler just to make sure you have a tagged element in the page template?

**Comment by nynevi** [comment]
just as a follow up, I've revised the implementation to be more robust. I unfortunately don't have code snippets to share but it works like this:

In React (or any other framework), high up in the component tree, I have an interval that keeps checking whether the tagged element with `data-iframe-height` has actually been mounted:
```js
const intervalId = setInterval(() => {
    const el = document.querySelector(
        "[data-iframe-height]",
    )

   if (el) {
      //send window.postMessage event to the parent that element has bee mounted
     clearInterval(intervalId)
   }
}, 100)
```

Then in the parent I am listening to `message` events:
```js
window.addEventListener('message', (message) => {
    //check if message is originating from inside of the iframe
    //and call iframe.iFrameResizer.resize()
})
```
