### ISSUE TITLE
Vue version, TypeError: Cannot destructure property 'title' of 'document.getElementById(...)' as it is null.

### ISSUE THREAD

**Issue by vodnicearv** [davidjbradshaw/iframe-resizer#1273]
Sometime we received this error: 
index.esm.js:20 Uncaught (in promise) TypeError: Cannot destructure property 'title' of 'document.getElementById(...)' as it is null.

**Screenshots**
<img width="743" alt="Screenshot 2024-06-19 at 15 12 07" src="https://github.com/davidjbradshaw/iframe-resizer/assets/14403446/30ceb5a3-334a-4fa9-a516-3795fcef2dfd">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version @iframe-resizer/vue: ^5.1.0
 
 Our code:
 
```
  <div class="my-12 sm:my-14" v-if="product.tilda && i18n(product.tilda)">
    <IframeResizer
        :src="i18n(product.tilda)"
        class="w-full"
    />
  </div>
```

**Comment by davidjbradshaw** [comment]
That's strange the error suggests the iframe is missing from the page. Anyway I've changed how I check `iframe.title` and added a check that the iframe is actually there, so this should hopefully be fixed in **v5.1.2**. which has just been published.

If it is still an issue, can you please make me a test page, as I'm unable to repro this.

I'm new to Vue, so would love any feedback on how you think the Vue component could be improved.

**Comment by vodnicearv** [comment]
thanks @davidjbradshaw ! you are awesome

**Comment by davidjbradshaw** [comment]
I'm still a bit confused by this, as you got that error 27 times, but that code is only called when you load a page into the iframe.

Does your site use a lot of pages in the iframe? Or is maybe Vue doing something I'm not expecting?

**Comment by vodnicearv** [comment]
no, I load only 1 page in iframe
