### ISSUE TITLE
Can't find doc for resizer version 4.2.11

### ISSUE THREAD

**Issue by aditya-kreditz** [davidjbradshaw/iframe-resizer#1361]
We are using version 4.2.11. But not able to find it anywhere. Can anyone share it?

**Comment by davidjbradshaw** [comment]
The V4 docs can be found at the following link.

https://github.com/davidjbradshaw/iframe-resizer/tree/v4/docs

However, I do recommend upgrading to V5, the library has come along way since v4 and is now simpler to use, has significantly better performance and is able to deal with a lot more content, without developer assistance.

https://iframe-resizer.com/upgrade/
