### ISSUE TITLE
Flickering: iFrame height seems to change every couple of seconds

### ISSUE THREAD

**Issue by Forge-Media** [davidjbradshaw/iframe-resizer#139]
Hi

I have the plugin setup and running however, I'm getting a problem once the iFrame height changes. The height changes correctly but then there is an odd flickering where the iFrame height seems to change every couple of seconds back to its onload height.

After I resize the iFrame back to its onload height the flickering stops. 

See here:
http://youtu.be/sb1RsUk9jRM

or here:
http://178.62.55.84/hosting/status/

**Comment by davidjbradshaw** [comment]
Your problem is that you have selected a height calculation that requires a downward resize to calculate if the page has down sized and then are running something on the page that means the code has to check if the page has resized. Try using a different height calculation method, or change it just while you do the popup. See the notes on this.

https://github.com/davidjbradshaw/iframe-resizer#heightcalculationmethod
