### ISSUE TITLE
iframe-resizer in JQM

### ISSUE THREAD

**Issue by lwbrown** [davidjbradshaw/iframe-resizer#147]
The iframe-resizer works great on my localhost as a stand-alone but I cannot get it to work in Jquery Mobile. No errors - but the console is empty of any iFrameSizer output. Any ideas? THANKS

**Comment by davidjbradshaw** [comment]
Someone else had this issue a while back and we never did get to the bottom of it. I think the issue is jqm manipulating something.

**Comment by paulbors** [comment]
Not for nothing, but could you try to reproduce the bug in jsFiddle.net with the iPhone emulator in XCode?

Perhaps all you need to do is actually trace through the code to see what's happening?

**Comment by davidjbradshaw** [comment]
Have a look at #36, have you tried the other ways of calculating the height? Been a few more added since that issue. From memory JQM does something strange with height of the body tag.

That said if your getting no logging messages I would check that it is running, as you should at least see four lines. Some frameworks like JQM have a nasty habit of catching all JS errors on a page, so you don't see when your own code crashes.
