### ISSUE TITLE
Store/Show URL of the i-Frame in parameter of parent Page containing the iframe?

### ISSUE THREAD

**Issue by michaelkarrer81** [davidjbradshaw/iframe-resizer#347]
Sorry this is more a question than a bug report.

Is there a way to store the current i-Frame URL somehow in the URL of the page where the i-Frame is hosted?
### Example:

Webpage A = "a.com" The wepage hosting the i-frame
Webpage F = "f.com" The webpage shown inside the i-frame (src)

Lets say we open site a.com with an URL 
http://a.com/page-wher-frame-is-stored
Inside we open the i-frame with URL 
http://f.com/start-page
Next the user navigates inside the i-frame and changes the URL inside the i-frame to 
http://f.com/second-page

Now i want the URL of site a updating to something like:
http://a.com/page-wher-frame-is-stored?iframe-[frame-id]="http://f.com/second-page"
or (probably even worse ;) )
http://a.com/page-wher-frame-is-stored/[frame-id]/second-page

So that the relative URL inside the i-frame is known/stored in the URL of webpage hosting the i-frame.

Thanks for any help! Even a "This is not possible, or should not be done because ... would help a lot"

**Comment by michaelkarrer81** [comment]
Ah sorry this was more or less already asked in #267. Simply overlooked it.

**Comment by davidjbradshaw** [comment]
OK, no problem, would be great if you could add an example to either ticket.

**Comment by michaelkarrer81** [comment]
Hello David, thank you for your answer. 

I would love to add an example but i am afraid that i do not fully understand what kind of example you have in mind. If my Example above is sufficient regarding the wanted functionality it would be a pleasure to add it to the other issue also!

Would it be possible to pay you or any java script programmer you might now to implement this feature asap. We would need it to do something good for the world: We support non profit organizations to collect donations but are missing this one feature to go live. :(

I am an python programmer so for me it is pretty hard to figure this out. I guess that an experienced java programmer could do it in one day? But the best would for sure be that this is implemented in core directly and well done! - So who would be better for the job than the inventor of this great java script.

I am quite desperate so any help would be really appreciated!

**Comment by davidjbradshaw** [comment]
Sorry been hyper busy and didn't noticed you'd add a comment to a closed post. Next time reopen it so it shows up in the open issues list.

Anyway interested to know if found a solution.

**Comment by speedpacer** [comment]
I'm also looking for such a feature, or a similar one.  I'm integrating Django with Trac where Trac is running in the iframe. The resizing works great but when a user clicks on a link within the iframe, I need the URL to show the full path and the parent page to reload and update that iframe.  Currently, it just changes the content in the iframe and the parent page and URL stay the same.  I'm also a Python guy with very little javascript experience so I'm a little lost.  Thank you for this contribution btw!  This is as close as I've been able to get to what I'm after.

**Comment by davidjbradshaw** [comment]
I understand the requirement now. I think it could be done with something like this.

Add the following to each page you load into the iFrame.
```html
<script>
	window.iFrameResizer = {
		readyCallback: function(){
			window.parentIFrame.sendMessage(location.href);
		}
	}
</script>
```

Then in the parent page [messagecallback](https://github.com/davidjbradshaw/iframe-resizer#messagecallback) callback to receive the message and do what ever you want with it.

**Comment by speedpacer** [comment]
Thanks for the quick reply. This makes perfect sense. Sadly, my results
have been either nothing happening, or it goes into an infinite loop of
loading the page in the frame.

The alert(messageData.message); shows the correct url.

To messageCallback, I added: document.getElementById('iframe').src =
messageData.message;

That's when it goes into a loop.

On Fri, Nov 18, 2016 at 5:33 AM, David J. Bradshaw <notifications@github.com

**Comment by davidjbradshaw** [comment]
@speedpacer Not sure what you are trying to achieve. What you have done their is to tell the iFrame tag to load the current page every time it loads.

**Comment by speedpacer** [comment]
Sorry I didn't get back sooner, I'm still having trouble with this but I'm in the middle of the production migration right now so I've set this aside as a known issue but not a show stopper.  

All I need to do is, when I click a link in the child page, I need the parent to navigate to that page so that the URL in the browser changes and can be bookmarked or copied and sent in an email, etc. What is currently happening is that I click on a link in the child page and only the content in the iframe changes but the URL in the browser stays the same. 

I did as you suggested and added the messageCallback which sent the correct URL to the parent to navigate to, but if I tell the parent to navigate to that page, both the child and the parent try to navigate to it and it goes into the loop.  But if I cancel the navigation in the child, I never get the messageCallback. 

I also tried setting the default target to parent in the child frame, but then it shows the entire child page in the browser without the parent.  

I'm sure it's something I'm doing wrong, not real familiar with Javascript, but I've tried everything I could google for several days and nothing has worked. I could set up an example and give you access to it if it would help. I'd be willing to pay for your time if necessary.
