### ISSUE TITLE
iFrame width resizes when clicking within iframe content

### ISSUE THREAD

**Issue by bigweld86** [davidjbradshaw/iframe-resizer#360]
Hi.

When I click inside the iframe, the width begins to shrink for every click. I'm not re-sizing the window, just clicking inside the iframe. Why is that?

This is my initial setup:

$('iframe').iFrameResize({
            autoResize: true,
            scrolling: false,
            sizeWidth: true,
            checkOrigin: [reports_server],
            log: true
        });

And this is the log after clicking:

[iFrameSizer][report-iframe] Trigger event lock off
rdPage.aspx?rdReport=rport&rdSecureKey=12345…:2 [iFrameSizer][report-iframe] --
rdPage.aspx?rdReport=rport&rdSecureKey=12345…:2 [iFrameSizer][report-iframe] Trigger event: Mouse Down
rdPage.aspx?rdReport=rport&rdSecureKey=12345…:2 [iFrameSizer][report-iframe] Trigger event lock on
rdPage.aspx?rdReport=rport&rdSecureKey=12345…:2 [iFrameSizer][report-iframe] Sending message to host page (report-iframe:594:1226:mousedown)
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Received: [iFrameSizer]report-iframe:594:1226:mousedown
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Checking connection is from allowed list of origins: https://mydomain.com
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Checking height is in range 0-Infinity
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Checking width is in range 0-Infinity
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Requesting animation frame
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] IFrame (report-iframe) height set to 594px
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] IFrame (report-iframe) width set to 1226px
rdPage.aspx?rdReport=rport&rdSecureKey=12345…:2 [iFrameSizer][report-iframe] Trigger event: Mouse Up
rdPage.aspx?rdReport=rport&rdSecureKey=12345…:2 [iFrameSizer][report-iframe] Sending message to host page (report-iframe:594:1223:mouseup)
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Received: [iFrameSizer]report-iframe:594:1223:mouseup
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Checking connection is from allowed list of origins: https://mydomain.com
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Checking height is in range 0-Infinity
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Checking width is in range 0-Infinity
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] Requesting animation frame
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] IFrame (report-iframe) height set to 594px
iframeResizer.js:129 [iFrameSizer][Host page: report-iframe] IFrame (report-iframe) width set to 1223px
rdPage.aspx?rdReport=rport&rdSecureKey=12345…:2 [iFrameSizer][report-iframe] Trigger event lock off
rdPage.aspx?rdReport=rport&rdSecureKey=12345…:2 [iFrameSizer][report-iframe] --

**Comment by davidjbradshaw** [comment]
Check your CSS.

**Comment by cperryk** [comment]
@bigweld86 Did you find any cause behind this in your code? I'm seeing this exact same behavior except for height — every time I click, the height shrinks by exactly 8px.

**Comment by davidjbradshaw** [comment]
The reason will most likely be that the element on your page that is used to calculate the height is set to be 8px smaller than the window. Check your CSS.

**Comment by kaliara** [comment]
@bigweld86, @cperryk and anyone else having this issue: you can also try switching the `heightCalculationMethod` property to something else (going back to the default worked for me). Just be sure to experiment with different browsers and situations (like having the iframe shrink instead of grow).

**Comment by juan0087** [comment]
I'm experiencing a similar issue, but in my case it increases the height when clicking anywhere inside the iframe. I checked the css and done multiple things and can't seem to find the root cause. 

https://congodesk.com/test-engine/

My Code:
`    <style>
      iframe {
        width: 1px;
        min-width: 100%;
      }
    </style>
    <iframe
      id="congoIframe"
      scrolling="no"
      src="https://book.congodesk.com/compact/demo-property"
      width="100%"
      frameBorder="0"
      data-embed="true"
    ></iframe>

    <script
      type="text/javascript"
      src="https://dl.dropboxusercontent.com/s/tmfhxa5mqsqhlqr/iframeResizer.min.js?dl=0"
      async
    ></script>
    <script>
      setTimeout(() => {
        iFrameResize(
          {
            maxHeight: 'infinity',
            maxWidth: 'infinity',
            minHeight: '100%',
            minWidth: '100%',
            scrolling: false,
            sizeHeight: true,
            log: true,
          },
          '#congoIframe'
        );
      }, 1000);
    </script>`

LOG:
`iframeResizer.contentWindow.min.js:9 [iFrameSizer][congoIframe] Trigger event: Mouse Down
iframeResizer.contentWindow.min.js:9 [iFrameSizer][congoIframe] Trigger event lock on
iframeResizer.contentWindow.min.js:9 [iFrameSizer][congoIframe] Sending message to host page (congoIframe:1071:1170:mousedown)
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Received: [iFrameSizer]congoIframe:1071:1170:mousedown
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Checking connection is from: https://book.congodesk.com
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Checking height is in range NaN-NaN
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Checking width is in range NaN-NaN
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Requesting animation frame
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] IFrame (congoIframe) height set to 1071px
iframeResizer.contentWindow.min.js:9 [iFrameSizer][congoIframe] Trigger event: Mouse Up
iframeResizer.contentWindow.min.js:9 [iFrameSizer][congoIframe] Sending message to host page (congoIframe:1110:1170:mouseup)
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Received: [iFrameSizer]congoIframe:1110:1170:mouseup
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Checking connection is from: https://book.congodesk.com
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Checking height is in range NaN-NaN
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Checking width is in range NaN-NaN
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] Requesting animation frame
iframeResizer.min.js?dl=0:8 [iFrameSizer][Host page: congoIframe] IFrame (congoIframe) height set to 1110px
iframeResizer.contentWindow.min.js:9 [iFrameSizer][congoIframe] Trigger event lock off
iframeResizer.contentWindow.min.js:9 [iFrameSizer][congoIframe] --`

I'd really appreciate any help!!
