### ISSUE TITLE
iFrameSizer][Host page: XZY] [Window focus] IFrame(XZY) not found

### ISSUE THREAD

**Issue by urshensler** [davidjbradshaw/iframe-resizer#497]
We use the iFrameResizer and we are verry happy with it. Thank you.

The reason for my question is the fact that the iFrameResizer prints warnings in the console after the deletion of an iFrame form the page.

`[iFrameSizer][Host page: XZY] [Window focus] IFrame(XZY) not found`

I know that there is a `close()` method to propperly remove the iFrame from the DOM and the iFrameResizer. Because we use a third-party library to reload some of the content of our site it is not possible to call the `close()` method.

So I propose a new config `ignoreNotFound` for the iFrameResizer. Instead of printing a warning to the console, iFrameResizer would stop to observe the iFrame if it can't find it anymore.

What do you think?

**Comment by pscdodd** [comment]
@urshensler: Perhaps you could add a mutation observer to the parent node of the iframe and then call close instead?

Von: urshensler [mailto:notifications@github.com]
Gesendet: Dienstag, 13. Juni 2017 12:30
An: davidjbradshaw/iframe-resizer <iframe-resizer@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [davidjbradshaw/iframe-resizer] iFrameSizer][Host page: XZY] [Window focus] IFrame(XZY) not found (#497)


We use the iFrameResizer and we are verry happy with it. Thank you.

The reason for my question is the fact that the iFrameResizer prints warnings in the console after the deletion of an iFrame form the page.

[iFrameSizer][Host page: XZY] [Window focus] IFrame(XZY) not found

I know that there is a close() method to propperly remove the iFrame from the DOM and the iFrameResizer. Because we use a third-party library to reload some of the content of our site it is not possible to call the close() method.

So I propose a new config ignoreNotFound for the iFrameResizer. Instead of printing a warning to the console, iFrameResizer would stop to observe the iFrame if it can't find it anymore.

What do you think?

**Comment by urshensler** [comment]
I thought about a mutatuion oberserver but i have not direct access to the parent node of the iFrame. So I have to observe the whole document body. I like to avoid that because of performance reasons.

**Comment by davidjbradshaw** [comment]
It would be easy enough to do, but I'm concerned that we have two many options already and think this is too much of an edge case to further expand the range of options.

**Comment by davidjbradshaw** [comment]
I would just ignore the warning
