### ISSUE TITLE
Bootstrap modal

### ISSUE THREAD

**Issue by cosmopolit** [davidjbradshaw/iframe-resizer#655]
Not resizing when guest frame contains a modal.

**Comment by davidjbradshaw** [comment]
If you add a link to an example of the issue, I will have a quick look

**Comment by nicholasbutlin** [comment]
I am also seeing an issue, which is perhaps different. 

Everything works exactly as expected except for when a bootstrap loading modal opens and closes after the page has repositioned. 

## Expected behaviour: 
parent scrolls to top, following a parentIframe.scrollTo call from the child 

## Actual Behaviour: 
if the loading modal is not opened (i.e. load time of the child is quick), parent scrolls. 
if the loading ,mode opens ( ui.e. load time longer than 200ms), the parent scrolls, but then is reset to the old page position when the modal closes. 

log: 
```
[iFrameSizer][evenergiIframe] No change in size detected
iframeResizer.contentWindow.js:187 [iFrameSizer][evenergiIframe] Sending message to host page (evenergiIframe:0:0:scrollTo)
iframeResizer.contentWindow.js:187 [iFrameSizer][evenergiIframe] Trigger event: mutationObserver: [object HTMLDivElement] attributes
iframeResizer.contentWindow.js:187 [iFrameSizer][evenergiIframe] No change in size detected
iframeResizer.js:145 [iFrameSizer][Host page: evenergiIframe] Received: [iFrameSizer]evenergiIframe:0:0:scrollTo
iframeResizer.js:145 [iFrameSizer][Host page: evenergiIframe] Checking connection is from: http://localhost:3001
iframeResizer.js:145 [iFrameSizer][Host page: evenergiIframe] Reposition requested from iFrame (offset x:0 y:0)
iframeResizer.js:668 setPagePosition
iframeResizer.js:145 [iFrameSizer][Host page: evenergiIframe] Set page position: 0,0
iframeResizer.js:145 [iFrameSizer][Host page: evenergiIframe] -- 
iframeResizer.contentWindow.js:187 [iFrameSizer][evenergiIframe] Trigger event: Transition End
iframeResizer.contentWindow.js:187 [iFrameSizer][evenergiIframe] No change in size detected
iframeResizer.contentWindow.js:187 [iFrameSizer][evenergiIframe] Trigger event: mutationObserver: [object HTMLBodyElement] childList
iframeResizer.contentWindow.js:187 [iFrameSizer][evenergiIframe] No change in size detected
```

 the modal closing calls this mutationObserver : 
iframeResizer.contentWindow.js:187 [iFrameSizer][evenergiIframe] Trigger event: mutationObserver: [object HTMLBodyElement] childList

which is causing the strange behaviour. 

However I have spent a couple of hours can't find why - neither scrollTo() or psetPagePosition() appear to be being called. 

I have also tried setting scrollCallback => false and repositioning directly, but the closing of the modal still repositions the page.

**Comment by nicholasbutlin** [comment]
And thanks very much @davidjbradshaw for this fantastic library!

**Comment by abdulsemiu-atanda** [comment]
I kinda have a similar problem 'cause when the modal when a tad bit long, it gets cut off on iPad (all is well with all other devices). I have tried increasing the `z-index` on the modal content to an insanely high value but doesn't seem to have any effect. any ideas on how to solve this problem will be nice. Thank you!

**Comment by abdulsemiu-atanda** [comment]
@davidjbradshaw Thanks for your quick reply. I'd play with more `height` calculation method to see if that helps

**Comment by nicholasbutlin** [comment]
@davidjbradshaw I'll have a look, but I think this is different issue to @abdulsemiu-atanda
