### ISSUE TITLE
Detect Infinity increasing height

### ISSUE THREAD

**Issue by victornpb** [davidjbradshaw/iframe-resizer#692]
I understand that the current start of the web maybe is impossible to determine the iframe size if the iframe contents is cyclic dependent on the frame size. E.g. `height:100vh;`

But there's any way to programmatically detect and prevent such content from breaking the host page? The iframe content is user generated.

**Comment by davidjbradshaw** [comment]
I don't see why that would not work

**Comment by oheightoneninetwo** [comment]
I have also been able to reproduce this with using min-height: 100vh and % on the child page. The iframeresizer gets stuck in a loop because view height is dependent on the size of the frame which is dependent on the content (due to iframeresizer). 

You could do the height calculation via JS on page load (based on the height of the parent - you could use the iframeresizer calls for this) albeit a messy solution, whatever way you try work around it the easiest method is to just not use % or vh for heights but that limits what you can do with the iframe. 

Another solution is to just not use the iframe resizing capabilities, have a fixed size iframe.

**Comment by davidjbradshaw** [comment]
Oh I see, I don't think their is an easy code fix for that. I can only suggest using `taggedElement` or you can create your own custom method to calculate the height inside the iframe.

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/options.md#heightcalculationmethod--widthcalculationmethod
