### ISSUE TITLE
can not disable or remove alerts

### ISSUE THREAD

**Issue by qxygene** [davidjbradshaw/iframe-resizer#803]
script creates alert pop ups on each reload. how to get rid of them?

**Comment by davidjbradshaw** [comment]
Their are no `alerts` in the codebase. Something else must be causing them and without seeing them it is impossible for me to comment

**Comment by qxygene** [comment]
thanks, but i get alerts >>>
https://snipboard.io/53WSVi.jpg

**Comment by qxygene** [comment]
found what cause it, 

function iFrameReadyMsgReceived()

createOutgoingMsg(iframeId),

when is remove it script stops working. any chance to fix this issue??

**Comment by davidjbradshaw** [comment]
It is not an issue with this library, those messages are sent between the iframe and the host page via postMessage. Any other code you have on you page can also listen to these messages and other code can send messages over the same connection.

To mitigate this, **iframe-resizer** ignores any messages that don't start with `[iframeResizer]`, it appears that you have some other code on your site that when faced with the same issue, instead of ignoring the message, chooses to alert it to the user.

There is nothing I can do about that. You will need to find that `alert` and remove it.
